"""
Author: Balaguru Sivasambagupta
GitHub: https://github.com/bala1802
"""

from langchain_community.tools.tavily_search import TavilySearchResults
from config import NUMBER_OF_WEB_SEARCH_RESULTS

"""
Initializes and configures an instance of the TavilySearchResults web search tool.

This function:
- Creates and configures an instance of TavilySearchResults with the number of search results to return, 
specified by the global constant NUMBER_OF_WEB_SEARCH_RESULTS.
"""
def initialize_web_search_tool():
    """
    Returns:
        web_search_tool (Any): An instance of TavilySearchResults configured with the specified number of search results.
    """
    web_search_tool = TavilySearchResults(k=NUMBER_OF_WEB_SEARCH_RESULTS)
    return web_search_tool

"""
Executes a web search using the specified search tool based on the user's query.

This function:
- Uses the provided web search tool to perform a search with the given user query.
- Retrieves and returns the search results generated by the web search tool.
"""
def execute_web_search(web_search_tool: TavilySearchResults, user_query: str):
    """
    Args:
        web_search_tool (TavilySearchResults): An instance of the TavilySearchResults class used to perform the search.
        user_query (str): The query string to be used for the web search.

    Returns:
        search_result (List): The results obtained from the web search. The type of the result depends on the implementation of TavilySearchResults.
    """
    search_result = web_search_tool.run(user_query)
    return search_result